CREATE TABLE IF NOT EXISTS `neft_synonyms` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `WORD` TINYTEXT NOT NULL,
  `SYNONYMS` MEDIUMTEXT NOT NULL,
  `SORT` SMALLINT NOT NULL DEFAULT '500',
  `UPDATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (`ID`)
);
